# Generated by Django 4.2.7 on 2023-11-18 02:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot_server', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='airport',
            name='latitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='airport',
            name='longitude',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
