# Generated by Django 4.2.7 on 2023-11-18 03:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot_server', '0002_alter_airport_latitude_alter_airport_longitude'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flight',
            name='air_system_delay',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='flight',
            name='air_time',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='flight',
            name='airline_delay',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='flight',
            name='arrival_delay',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='flight',
            name='arrival_time',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='flight',
            name='cancellation_reason',
            field=models.CharField(blank=True, max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='flight',
            name='cancelled',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='flight',
            name='day',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='flight',
            name='day_of_week',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='flight',
            name='departure_delay',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='flight',
            name='departure_time',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='flight',
            name='distance',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='flight',
            name='diverted',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='flight',
            name='elapsed_time',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='flight',
            name='flight_number',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='flight',
            name='late_aircraft_delay',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='flight',
            name='month',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='flight',
            name='scheduled_arrival',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='flight',
            name='scheduled_departure',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='flight',
            name='scheduled_time',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='flight',
            name='security_delay',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='flight',
            name='tail_number',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='flight',
            name='taxi_in',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='flight',
            name='taxi_out',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='flight',
            name='weather_delay',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='flight',
            name='wheels_off',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='flight',
            name='wheels_on',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='flight',
            name='year',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
